INSERT INTO `SITE_DB`.`system_concept_groups` (`group_no`, `name`)
VALUES
	('1','Natur og miljø'),
	('2','Liv'),
	('3','Rum, form'),
	('4','Størrelse, mængde, tal, grad'),
	('5','Forhold, egenskab'),
	('6','Tid'),
	('7','Sanseindtryk, tilstandsformer'),
	('8','Sted og bevægelse'),
	('9','Vilje og handling'),
	('10','Følelser'),
	('11','Tænkning'),
	('12','Tegn, meddelelse, sprog'),
	('13','Videnskab'),
	('14','Kunst og kultur'),
	('15','Socialt liv'),
	('16','Mad og drikke'),
	('17','Sport og fritid'),
	('18','Samfund'),
	('19','Apparater, teknik'),
	('20','Økonomi, finans'),
	('21','Ret, etik'),
	('22','Religion, overnaturlig');